const fs = require("fs");
const path = 'src/pages/EditProfile.jsx';
let content = fs.readFileSync(path, 'utf8');
const pattern = /<label className="text-sm font-medium text-slate-700 dark:text-slate-200 cursor-pointer">\s*<input[\s\S]*?setCoverVideoStart\(0\);\s*\};\s*\};\s*\}\)\s*\}\}\s*\/?>\s*Subir video de portada[\s\S]*?{coverVideoFile && \(\s*<button[\s\S]*?coverVideoMutation.isPending \? "Guardando..." : "Guardar video de portada"\}\s*<\/button>\s*\)\s*}/;
if (!pattern.test(content)) {
  throw new Error('No se encontró el bloque de video de portada a reemplazar');
}
const replacement = [
  '<label className="text-sm font-medium text-slate-700 dark:text-slate-200 cursor-pointer">',
  '              <input',
  '                type="file"',
  '                accept="video/*"',
  '                className="hidden"',
  '                onChange={(e) => {',
  '                  const file = e.target.files?.[0] || null;',
  '                  if (file && file.size > 20 * 1024 * 1024) {',
  '                    alert("El video no puede superar 20MB");',
  '                    return;',
  '                  }',
  '                  setCoverVideoFile(file);',
  '                  if (file) {',
  '                    const url = URL.createObjectURL(file);',
  '                    const vid = document.createElement("video");',
  '                    vid.src = url;',
  '                    vid.onloadedmetadata = () => {',
  '                      const dur = vid.duration;',
  '                      setCoverVideoDuration(dur);',
  '                      setCoverVideoStart(0);',
  '                    };',
  '                  }',
  '                }}',
  '              />',
  '              Subir video de portada (máx. 20MB, clip de 3 o 5s)',
  '            </label>',
  '            <div className="flex items-center gap-2 text-xs text-slate-600 dark:text-slate-300">',
  '              <span>Duración:</span>',
  '              {[3, 5].map((len) => (',
  '                <button',
  '                  type="button"',
  '                  key={len}',
  '                  onClick={() => {',
  '                    setCoverClipLength(len);',
  '                    setCoverVideoStart((prev) =>',
  '                      Math.min(prev, Math.max(0, (coverVideoDuration || len) - len))',
  '                    );',
  '                  }}',
  '                  className={`px-2 py-1 rounded-full border ${',
  '                    coverClipLength === len',
  '                      ? "bg-indigo-600 text-white border-indigo-600"',
  '                      : "border-slate-300 dark:border-slate-700"',
  '                  }`}',
  '                >',
  '                  {len}s',
  '                </button>',
  '              ))}',
  '            </div>',
  '            {coverVideoDuration > 0 && (',
  '              <div className="text-xs text-slate-500">',
  '                Selecciona inicio (clip {coverClipLength}s):{" "}',
  '                <input',
  '                  type="range"',
  '                  min="0"',
  '                  max={Math.max(0, coverVideoDuration - coverClipLength)}',
  '                  step="0.1"',
  '                  value={coverVideoStart}',
  '                  onChange={(e) => setCoverVideoStart(Number(e.target.value))}',
  '                />',
  '                <span className="ml-2">',
  '                  {coverVideoStart.toFixed(1)}s - {(coverVideoStart + coverClipLength).toFixed(1)}s',
  '                </span>',
  '              </div>',
  '            )}',
  '            {coverVideoFile && (',
  '              <button',
  '                type="button"',
  '                onClick={() => coverVideoMutation.mutate(coverVideoFile)}',
  '                className="px-3 py-2 rounded-lg bg-indigo-600 text-white text-sm font-semibold hover:bg-indigo-500 disabled:opacity-50"',
  '                disabled={coverVideoMutation.isPending}',
  '              >',
  '                {coverVideoMutation.isPending ? "Guardando..." : "Guardar video de portada"}',
  '              </button>',
  '            )}',
].join("\n");
content = content.replace(pattern, replacement);
fs.writeFileSync(path, content, 'utf8');
console.log('Bloque de video de portada actualizado');
