export const EMOTIONS = [
  { emotion: "alegria", name: "Alegría/Euforia", color: "#FFD700" },
  { emotion: "felicidad", name: "Felicidad", color: "#FFA500" },
  { emotion: "amor", name: "Amor/Cariño", color: "#FF69B4" },
  { emotion: "gratitud", name: "Gratitud", color: "#FFC125" },
  { emotion: "esperanza", name: "Esperanza/Optimismo", color: "#87CEEB" },
  { emotion: "calma", name: "Calma/Serenidad", color: "#ADD8E6" },
  { emotion: "entusiasmo", name: "Entusiasmo", color: "#FF8C00" },
  { emotion: "inspiracion", name: "Inspiración", color: "#DDA0DD" },
  { emotion: "asombro", name: "Asombro", color: "#40E0D0" },
  { emotion: "orgullo", name: "Orgullo", color: "#FF6347" },
  { emotion: "tristeza", name: "Tristeza", color: "#4682B4" },
  { emotion: "melancolia", name: "Melancolía", color: "#708090" },
  { emotion: "angustia", name: "Angustia", color: "#6A5ACD" },
  { emotion: "ansiedad", name: "Ansiedad", color: "#D8BFD8" },
  { emotion: "frustracion", name: "Frustración", color: "#CD5C5C" },
  { emotion: "irritacion", name: "Irritación/Molestia", color: "#FF6347" },
  { emotion: "soledad", name: "Soledad", color: "#191970" },
  { emotion: "desesperacion", name: "Desesperación", color: "#2F4F4F" },
  { emotion: "nostalgia", name: "Nostalgia", color: "#8B008B" },
  { emotion: "reflexion", name: "Reflexión/Melancolía", color: "#5F9EA0" },
  { emotion: "vulnerabilidad", name: "Vulnerabilidad", color: "#DB7093" },
  { emotion: "ironia", name: "Ironía", color: "#C0C0C0" },
  { emotion: "neutral", name: "Neutral", color: "#D3D3D3" },
  { emotion: "sorpresa", name: "Sorpresa", color: "#FFFACD" },
  { emotion: "curiosidad", name: "Curiosidad", color: "#90EE90" },
  { emotion: "determinacion", name: "Determinación", color: "#556B2F" },
  { emotion: "humor", name: "Humor", color: "#FFFFE0" },
];

export const EMOTION_MODES = {
  AUTO: "auto",
  MANUAL: "manual",
  HIDDEN: "hidden",
};
