export const reelData = [
  { url: "https://img-9gag-fun.9cache.com/photo/aGyrPRn_460svav1.mp4", category: "oldmeme" },
  { url: "https://img-9gag-fun.9cache.com/photo/a0eDmbz_460svav1.mp4", category: "oldmeme" },
  { url: "https://img-9gag-fun.9cache.com/photo/amoOD26_460svav1.mp4", category: "anime" },
  { url: "https://img-9gag-fun.9cache.com/photo/abALj3v_460svav1.mp4", category: "anime" },
  { url: "https://img-9gag-fun.9cache.com/photo/aGyrPwn_460sv.mp4", category: "news" },
  { url: "https://img-9gag-fun.9cache.com/photo/ajP3pZR_460sv.mp4", category: "cosplay" },
  { url: "https://img-9gag-fun.9cache.com/photo/aPAVNqg_460svav1.mp4", category: "memes" },
  { url: "https://img-9gag-fun.9cache.com/photo/a2vABnD_460sv.mp4", category: "games" },
  { url: "https://img-9gag-fun.9cache.com/photo/azxv68j_460svav1.mp4", category: "wtf" },
  { url: "https://img-9gag-fun.9cache.com/photo/aW4eKAx_460svav1.mp4", category: "relationship" },
  { url: "https://img-9gag-fun.9cache.com/photo/aoyGBp0_460sv.mp4", category: "music" },
  { url: "https://img-9gag-fun.9cache.com/photo/avyBYEX_460svav1.mp4", category: "motorvehicles" },
  { url: "https://img-9gag-fun.9cache.com/photo/aYQvzwx_460svav1.mp4", category: "animals" },
  { url: "https://img-9gag-fun.9cache.com/photo/avyBbLX_460svav1.mp4", category: "science" },
  { url: "https://img-9gag-fun.9cache.com/photo/aRB8bZA_460sv.mp4", category: "sports" },
  { url: "https://img-9gag-fun.9cache.com/photo/an70pyo_460sv.mp4", category: "food" },
  { url: "https://img-9gag-fun.9cache.com/photo/an70AXb_460sv.mp4", category: "lifestyle" },
  { url: "https://img-9gag-fun.9cache.com/photo/ajP32Q1_460sv.mp4", category: "politics" },
  { url: "https://img-9gag-fun.9cache.com/photo/aKGXb4Q_460sv.mp4", category: "comic" },
  { url: "https://img-9gag-fun.9cache.com/photo/aRB8xAM_460svav1.mp4", category: "wholesome" },
];
